version: '3'
services:
    mysql:
        container_name: uxguide_mysql
        build:
            context: ./mysql
            args:
                - MYSQL_ROOT_PASSWORD=failnicely
                - MYSQL_USER=guide
                - MYSQL_PASSWORD=failnicely
                - MYSQL_DATABASE=uxguide
        ports:
            - "3305:3306"
        volumes:
            - /var/lib/mysql
        command: [mysqld, --character-set-server=utf8, --collation-server=utf8_general_ci]

