mysql:
    container_name: mysql_besoul
    image: mysql:latest
    environment:
        - MYSQL_ROOT_PASSWORD=failnicely
        - MYSQL_USER=besoul
        - MYSQL_PASSWORD=failnicely
        - MYSQL_DATABASE=besoul
    ports:
        - "3305:3306"
    volumes:
        - /var/lib/mysql
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_general_ci]
